### ISSUE TITLE
transform NE annotations into hyperlinked canonical references

### ISSUE THREAD

**Issue by mromanello** [AjaxMultiCommentary/ajmc-multicommentary#14]
There is a dependency with this ingestion pipeline issue: https://github.com/AjaxMultiCommentary/ajmc/issues/16

**Comment by mromanello** [comment]
@pletcher Fleshing out this issue – apologies for not having done it earlier
<img width="1920" alt="named_entity_layers_example_white_background (1)" src="https://github.com/AjaxMultiCommentary/ajmc-multicommentary/assets/310693/4d01f072-5f08-4d48-93ff-483fe8637dd0">

- entities that make up a canonical reference will be contained/nested within in a `primary-full` entity/container (once https://github.com/AjaxMultiCommentary/ajmc/issues/16 is fixed)
- "inside" a `primary-full` there can be: a) `person.author` + `work.primlit` + `scope` or b) `work.primlit` + `scope` – all other cases will be too underspecified to be resolved into a CTS URN
- to determine the CTS URN we will need to: take the Wikidata QID of the `work.primlit` entity, resolve it to a CTS URN and then concatenate it with a (cleaned up) scope
- for all other cases of entities having a Wikidata QID but not contained in a `primary-full` we could transform them into links to the corresponding Wikidata page

**Comment by mromanello** [comment]
I believe this was done using Adobe Illustrator, but inception has a somehow similar bubble-based display. However, there is no need to emulate this in the glossa viewer. The current rendering as hyperlinks (cfr. image) is sufficient and less confusing, I think. What imo is crucial in this feature is the link target of each canonical reference (Perseus' DL via CTS URN). 

![Screenshot 2024-02-07 at 13 28 24](https://github.com/AjaxMultiCommentary/ajmc-multicommentary/assets/310693/fda96b73-c905-433b-90a9-9380b76b604a)

**Comment by pletcher** [comment]
I think this is resolved by https://github.com/AjaxMultiCommentary/ajmc-multicommentary/commit/7b883f9f2ed33815daffd8dabd98b33e5ea9eda8 (barring any bugs).

It's a little tricky to check for, but I think Tournier @ v. 1 provides the easiest gloss to check.
